### ISSUE TITLE
Problem in processing fits file

### ISSUE THREAD

**Issue by steveschulze** [Samreay/Marz#149]
Hi,

I wrote a 1D spectrum to a fits file using python. The spectrum is properly displayed on the Marz website but no matching is performed. The command-line tool (version 1.3.8) processes the fits file but stalls when it is supposed to write out the results. The output from the debugger and the fits file are attached.

Do you have an idea why not matching is performed?

Cheers,

Steve

[cont_1_debug.log](https://github.com/Samreay/Marz/files/1530886/cont_1_debug.log)
[cont_1.fits.zip](https://github.com/Samreay/Marz/files/1530893/cont_1.fits.zip)

**Comment by Samreay** [comment]
Hi Steve,

Am currently traveling so haven't looked at the fits file, but managed to
open the log on my phone. I suspect the issue is that Marz requires an
input variance and you have not set one. To essentially ignore the
variance, pass in an array of one's the same shape as your flux under the
VARIANCE extension name.

Let me know if that fixes the issue.

Cheers

**Comment by steveschulze** [comment]
Hi Sam,

Thanks. Now it works like a charm!

Cheers,

Steve

**Comment by Samreay** [comment]
Glad it was a simple fix!
