### ISSUE TITLE
Uncertainties from Cross Correlation 

### ISSUE THREAD

**Issue by GeorgeRidgeway** [Samreay/Marz#152]
Hello,

I am using MARZ to calculate redshifts for galaxy spectra that I have. I was wondering if there is a way to obtain an uncertainty on the redshift that MARZ outputs from the associated XCor value? Is there a way to recover the XCor function so that we could measure the FWHM off the peak?

Thank you,

George

**Comment by Samreay** [comment]
Hey George! I dont support this out of the box, mostly because when we did our own initial implementation, we found that using things like the FWHM or width of the peak was not a good way to quantify uncertainty, and doing it like that vastly overestimated the amount of uncertainty in a fit (sometimes by more than an order of magnitude). I know Anthony Carr (UQ) is working right now to export the xcor values also for uncertainty analysis, I'd suggest reaching out to him and seeing if he's made any good progress. anthony.carr@uq.net.au 

Best of luck mate!
